CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "ProfessionalTypes" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    CONSTRAINT "PK_ProfessionalTypes" PRIMARY KEY ("Id")
);

CREATE TABLE "Roles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" text NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "ModifiedOn" timestamp with time zone,
    "IsDisabled" boolean NOT NULL,
    "SubscriptionLevel" integer NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "RoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Homes" (
    "Id" uuid NOT NULL,
    "AddressLine2" character varying(255),
    "City" character varying(100),
    "Country" character varying(100),
    "Latitude" double precision,
    "Longitude" double precision,
    "Name" character varying(100) NOT NULL,
    "PostalCode" character varying(20),
    "StreetAddress" character varying(255),
    "StateProvince" character varying(100),
    "CreatedOn" timestamp with time zone NOT NULL,
    "ModifiedOn" timestamp with time zone,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_Homes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Homes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Professionals" (
    "Id" uuid NOT NULL,
    "BusinessName" character varying(255),
    "BusinessPhoneNumber" character varying(50),
    "City" text,
    "Country" text,
    "EmailAddress" character varying(100),
    "Name" character varying(255) NOT NULL,
    "PersonalPhoneNumber" character varying(50),
    "PostalCode" character varying(20),
    "ProfessionalTypeId" uuid NOT NULL,
    "StateProvince" character varying(100),
    "StreetAddress" character varying(255),
    "WebsiteUrl" character varying(255),
    "CreatedOn" timestamp with time zone NOT NULL,
    "ModifiedOn" timestamp with time zone,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_Professionals" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Professionals_ProfessionalTypes_ProfessionalTypeId" FOREIGN KEY ("ProfessionalTypeId") REFERENCES "ProfessionalTypes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Professionals_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Rooms" (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "HomeId" uuid NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "ModifiedOn" timestamp with time zone,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_Rooms" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Rooms_Homes_HomeId" FOREIGN KEY ("HomeId") REFERENCES "Homes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "InventoryItems" (
    "Id" uuid NOT NULL,
    "HomeId" uuid NOT NULL,
    "RoomId" uuid,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "Price" double precision,
    "SerialNumber" character varying(50),
    "CreatedOn" timestamp with time zone NOT NULL,
    "ModifiedOn" timestamp with time zone,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_InventoryItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InventoryItems_Homes_HomeId" FOREIGN KEY ("HomeId") REFERENCES "Homes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_InventoryItems_Rooms_RoomId" FOREIGN KEY ("RoomId") REFERENCES "Rooms" ("Id")
);

CREATE INDEX "IX_Homes_UserId" ON "Homes" ("UserId");

CREATE INDEX "IX_InventoryItems_HomeId" ON "InventoryItems" ("HomeId");

CREATE INDEX "IX_InventoryItems_RoomId" ON "InventoryItems" ("RoomId");

CREATE INDEX "IX_InventoryItems_UserId" ON "InventoryItems" ("UserId");

CREATE INDEX "IX_Professionals_ProfessionalTypeId" ON "Professionals" ("ProfessionalTypeId");

CREATE INDEX "IX_Professionals_UserId" ON "Professionals" ("UserId");

CREATE INDEX "IX_RoleClaims_RoleId" ON "RoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "Roles" ("NormalizedName");

CREATE INDEX "IX_Rooms_HomeId" ON "Rooms" ("HomeId");

CREATE INDEX "IX_UserClaims_UserId" ON "UserClaims" ("UserId");

CREATE INDEX "IX_UserLogins_UserId" ON "UserLogins" ("UserId");

CREATE INDEX "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "Users" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "Users" ("NormalizedUserName");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250221053618_Initial', '9.0.1');

COMMIT;

